image::https://github.com/jetty-project/jetty-cluster-orchestrator/workflows/GitHub%20CI/badge.svg[GitHub CI Badge]

= Jetty Cluster Orchestrator Project

Jetty's `Cluster Orchestrator` is an API to ease writing tests that execute code over different JVMs, locally or across networks.

== Maven Dependencies

The project is structured as a multi-module Maven build with three modules:

=== Core API Module (Always Required)

[source,xml]
----
<dependency>
    <groupId>org.mortbay.jetty.orchestrator</groupId>
    <artifactId>jetty-cluster-orchestrator-api</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
----

The API module provides the core orchestration functionality including:

* `Cluster`, `ClusterConfiguration`, and core interfaces
* `LocalHostLauncher` for local JVM processes 
* Coordination tools (`Barrier`, `AtomicCounter`)
* RPC framework and embedded ZooKeeper

=== SSH Support (Optional)

For remote execution over SSH, add:

[source,xml]
----
<dependency>
    <groupId>org.mortbay.jetty.orchestrator</groupId>
    <artifactId>jetty-cluster-orchestrator-ssh</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
----

This module provides:

* `SshRemoteHostLauncher` for SSH-based remote hosts
* `SFTPNodeFileSystem` for remote file access over SFTP
* Requires SSH public key authentication

=== Kubernetes Support (Optional)

For Kubernetes pod execution, add:

[source,xml]
----
<dependency>
    <groupId>org.mortbay.jetty.orchestrator</groupId>
    <artifactId>jetty-cluster-orchestrator-k8s</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
----

This module provides:

* `KubernetesRemoteHostLauncher` for Kubernetes pod hosts
* `KubernetesNodeFileSystem` for remote file access via kubectl exec
* Requires kubeconfig with pod creation permissions

== Multi-Module Build Commands

[source,bash]
----
# Build all modules
mvn clean install

# Build specific module
mvn clean install -pl jetty-cluster-orchestrator-api
mvn clean install -pl jetty-cluster-orchestrator-ssh  
mvn clean install -pl jetty-cluster-orchestrator-k8s

# Test specific module
mvn test -pl jetty-cluster-orchestrator-api
mvn test -pl jetty-cluster-orchestrator-k8s

# Run the Kubernetes integration tests. They start a throwaway k3s cluster in Docker,
# so a running Docker daemon is all they need. Add -Dkubernetes.config.path=... to run
# them against an existing cluster instead.
mvn clean install -pl jetty-cluster-orchestrator-k8s
----

== Cluster Orchestrator API

=== A word of warning

This cluster orchestration library is not meant to be used for writing production code! Any form of network failure will make
this library fail without even an attempt at managing nor recovering the problem. This is a reasonable limitation for the scope
of this library which is to ease writing multi-machine tests.

=== Required java version

Starting with version 2.0.0, Java 17 is necessary. Version 1.x needs Java 11, and version 1.0.3 is the last one compatible with Java 8.

=== Configuring a JVM cluster

Creating a `ClusterConfiguration` instance is the first step to creating a cluster of JVMs. 

[source,java]
----
ClusterConfiguration cfg = new SimpleClusterConfiguration()
    .nodeArray(new LocalNodeArrayConfiguration("my-array")  // (1)
        .node("1")                                          // (2)
        .node("2"));
----

. Add a `NodeArray` named `my-array`. A node array is a logical group of JVMs that are usually meant to do the same thing.
 Any number of `NodeArray` s can be added to a cluster, as long as they have unique names.
 The type of node array picks where its JVMs run: `LocalNodeArrayConfiguration` runs them on the local machine.
. Add two nodes to the cluster, identified by the strings `&quot;1&quot;` and `&quot;2&quot;`. Node identifiers must be unique
 within a node array.

=== Using a configured JVM cluster

Creating a `Cluster` instance using a `ClusterConfiguration` sets the cluster up then allows one to do useful things with it.

[source,java]
----
try (Cluster cluster = new Cluster(cfg))                // (1)
{
    NodeArray myArray = cluster.nodeArray("my-array");  // (2)
    NodeArrayFuture f = myArray.executeOnAll(tools ->   // (3)
    {
        System.out.println("hello, world!");            // (4)
    });
    f.get(5, TimeUnit.SECONDS);                         // (5)
}
----

. Create a `Cluster` instance from the configuration.
. Fetch the configured `NodeArray` named `my-array`.
. Execute a lambda on all the nodes of the `NodeArray`.
. Print `hello, world!` on the remote node. Since the output is echoed back, that appears on the current terminal.
. Block until all nodes finished executing the lambda, or until a 5 seconds timeout elapsed.

Running the above code will print the following on `System.out`:

[source,asciidoc]
----
hello, world!
hello, world!
----

which is expected as the lambda was executed on a `NodeArray` that contains two `Node` s, hence it got executed twice.

=== Under the hood

The above example triggered the creation of two JVMs: one for each node. Then the lambda passed to `executeOnAll()` was
serialized and sent to those two JVMs which deserialized and executed it.
To make the deserialization possible, the classpath of the JVM executing the code above was copied to a sub-folder
of `${HOME}/.jco` and given as the classpath argument of the created JVMs. The `java` command on your `${PATH}` was used to
create those two JVMs. Finally, when the `Cluster` instance was closed, all processes were shut down, all created files were
deleted and all other resources were reclaimed.

=== Over the network

If you want to use machines over the network, swap the node array for an `SshNodeArrayConfiguration`, name the machines,
and give the cluster an `SshRemoteHostLauncher`:

[source,java]
----
ClusterConfiguration cfg = new SimpleClusterConfiguration()
    .hostLauncher(new SshRemoteHostLauncher())
    .nodeArray(new SshNodeArrayConfiguration("my-array")
        .node("1", "server-1")
        .node("2", "server-2"));
----

Running the above example with this configuration would create a JVM on a machine called `server-1`, another on a machine called
`server-2` and execute the lambda on both of them, which would end up printing the exact same output as the standard output and
error are piped from the remote machines to the local one. So by just changing the node array type and the launcher, you can
decide if the code has to run locally or remotely.

The way the JVMs are created on the remote machines is the same as in the local case: the classpath is copied, then the `java`
command is used to create a JVM. The only difference is that this time copying and creating a process is done over SSH
so it is assumed that the remote machines are reachable over SSH with public key auth pre-configured. The keys in `${HOME}/.ssh`
are going to be used for that purpose.

IMPORTANT: To use SSH functionality, you must include the `jetty-cluster-orchestrator-ssh` module dependency in your project.

=== Specifying the JVM

If you want to use a specific JVM over the one in your path, you can pass a `Jvm` instance to the `ClusterConfiguration`:

[source,java]
----
ClusterConfiguration cfg = new SimpleClusterConfiguration()
    .jvm(new Jvm((fs, h) -> "/some/path/to/jdk11/bin/java", "-Xmx4g", "-Dmy.prop=SomeValue"))
    .nodeArray(new LocalNodeArrayConfiguration("my-array")
        .node("1")
        .node("2"));
----

The configuration above is identical to the previous one, except that the `/some/path/to/jdk11/bin/java` command is going to be
used to create the JVM process with the `-Xmx4g -Dmy.prop=SomeValue` arguments passed on its command line.

Or you could be more specific by only configuring the JVM on the `NodeArray`:

[source,java]
----
ClusterConfiguration cfg = new SimpleClusterConfiguration()
    .nodeArray(new LocalNodeArrayConfiguration("my-array")
        .jvm(new Jvm((fs, h) -> "/some/path/to/jdk11/bin/java", "-Xmx4g", "-Dmy.prop=SomeValue"))
        .node("1")
        .node("2"));
----

In this case, only the `my-array` `NodeArray` would use the configured JVM but since it is the only configured node array,
this makes no difference overall. But when you want to run multiple `NodeArray` s it becomes useful to be able to different
JVMs for each `NodeArray` and eventually have a default one for the cluster that is going to be used for `NodeArray` s
whose JVM was not set.

Please note that the `/some/path/to/jdk11/bin/java` executable argument is a lambda that accepts a `java.nio.file.FileSystem`
and a `String` so that the remote filesystem of the machine whose name is specified by the string can be browsed to find the
JVM executable.
This is useful if you use machines with heterogenous operating systems, or simply have installed your JVMs in different
locations on your machines.

=== Synchronizing the lambdas

The lambda passed to `executeOnAll` is given a `tools` parameter which is an instance of `ClusterTools`. With it, you have access
to clustered atomic counters and clustered barriers that you can use to exchange data across lambdas or to synchronize them.

The `Cluster` class also has a `tools()` method that returns a `ClusterTools` instance you can use to synchronize the lambdas
with the test code.

=== Downloading reports

If the lambdas you execute code that writes to the local disk, those files will be deleted when the `Cluster` instance gets closed,
assuming that you create your files in the current working directory. It is sometimes useful to have each node write a report locally
then collect all those reports and eventually merge and transform them.

[source,java]
----
ClusterConfiguration cfg = new SimpleClusterConfiguration()             // (1)
    .hostLauncher(new SshRemoteHostLauncher())
    .nodeArray(new SshNodeArrayConfiguration("my-array")
        .node("1", "server-1")
        .node("2", "server-2"));

try (Cluster cluster = new Cluster(cfg))
{
    NodeArray myArray = cluster.nodeArray("my-array");
    NodeArrayFuture f = myArray.executeOnAll(tools ->
    {
        try (FileOutputStream fos = new FileOutputStream("data.txt"))
        {
            fos.write("hello file!".getBytes(StandardCharsets.UTF_8));  // (2)
        }
    });
    f.get(5, TimeUnit.SECONDS);

    for (String id : myArray.ids())                                     // (3)
    {
        File outputFolder = new File("reports", id);
        outputFolder.mkdirs();
        try (FileOutputStream fos = new FileOutputStream(new File(outputFolder, "data.txt")))
        {
            Path path = myArray.rootPathOf(id).resolve("data.txt");     // (4)
            Files.copy(path, fos);
        }
    }
}
----

. Create a cluster with a single `NodeArray` named `my-array` that contains two nodes.
. Execute a lambda on each of those two nodes to create a file called `data.txt` into the current working directory.
. Iterate over the IDs of the nodes of the `my-array` `NodeArray`.
. `NodeArray.rootPathOf(id)` returns a NIO `Path` instance that points to the node's current working directory. The NIO
  `Path` API can be used to browse folders or read files which is done in this case to copy the files over to the local machine.

After running this test, you should have a hierarchy on the local filesystem that looks like the following:

[source]
----
 reports
 +-- 1
 |   +-- data.txt
 +-- 2
     +-- data.txt
----

A NIO `FileSystem` is created for each remote machine that transparently works across the SSH connection, or locally
in case the node's machine is `localhost`. Please just note that the transparent remote filesystem is read-only.

== Configuration Properties

The Jetty Cluster Orchestrator supports several system properties to configure ZooKeeper connectivity and retry behavior.
These properties are useful for adapting the cluster behavior to different network environments or CI/CD systems.

=== ZooKeeper Connection Configuration

[cols="1,1,2,1"]
|===
|Property |Default |Description |Example

|`jco.curator.retry.baseSleepTimeMs`
|`1000`
|Base delay between ZooKeeper retry attempts in milliseconds
|`-Djco.curator.retry.baseSleepTimeMs=500`

|`jco.curator.retry.maxRetries`
|`3`
|Maximum number of retry attempts for ZooKeeper operations
|`-Djco.curator.retry.maxRetries=5`

|`jco.curator.sessionTimeoutMs`
|`30000`
|ZooKeeper session timeout in milliseconds
|`-Djco.curator.sessionTimeoutMs=15000`

|`jco.curator.connectionTimeoutMs`
|`15000`
|ZooKeeper initial connection timeout in milliseconds
|`-Djco.curator.connectionTimeoutMs=10000`
|===

==== Configuration Examples

For environments with unstable networks (e.g., CI systems with resource contention):

[source,bash]
----
mvn test -Djco.curator.retry.maxRetries=5 -Djco.curator.retry.baseSleepTimeMs=500
----

For faster test execution in stable environments:

[source,bash]
----
mvn test -Djco.curator.sessionTimeoutMs=10000 -Djco.curator.connectionTimeoutMs=5000
----

The retry policy uses exponential backoff, so with default settings of 3 retries and 1000ms base delay,
the actual delays will be approximately: 1s, 2s, 4s before giving up.

IMPORTANT: Setting `maxRetries` to 0 will disable retries entirely, which may cause connection failures
in environments with temporary network hiccups during test execution.

=== Node Health Check Configuration

[cols="2,1,2,2"]
|===
|Property |Default |Description |Example

|`org.mortbay.jetty.orchestrator.skipExitOnHealthCheckFailure`
|`false`
|Make a node that missed too many health checks stop itself instead of killing its JVM
|`-Dorg.mortbay.jetty.orchestrator.skipExitOnHealthCheckFailure=true`
|===

Every node watches the health checks the cluster sends it, and gives up when too many are missed.
A node usually has a process of its own, so it calls `System.exit` to get rid of itself. Nodes on
`localhost` do not: they run in the JVM that started the cluster, so exiting takes that JVM down too.

Set this property to `true` when that JVM has to survive, a surefire fork for instance. The node then
shuts itself down and the cluster reports the failure as an exception. Nodes with their own process
still exit, which is what the health check is for.

[source,bash]
----
mvn test -Dorg.mortbay.jetty.orchestrator.skipExitOnHealthCheckFailure=true
----

=== Kubernetes mode

Nodes can also be launched as Kubernetes pods. See link:KUBERNETES.md[KUBERNETES.md] for the full API reference.

IMPORTANT: To use Kubernetes functionality, you must include the `jetty-cluster-orchestrator-k8s` module dependency in your project.

==== Running the Kubernetes tests

The Kubernetes integration tests start a throwaway https://k3s.io[k3s] cluster in Docker through
Testcontainers, so a running Docker daemon is the only prerequisite. They are skipped when Docker
is unavailable.

[source,bash]
----
mvn clean install
----

To run them against a cluster you already have instead:

[source,bash]
----
mvn clean install \
  -Dkubernetes.config.path=$HOME/.kube/config \
  -Dk8s.image=eclipse-temurin:21-jre \
  -Dk8s.namespace=foo-bar
----

`k8s.image` is the image the node pods run (it needs a JRE and `tar`) and `k3s.image` picks the k3s
image used for the throwaway cluster.
